---

extends: "airbnb-base"

parserOptions:
  ecmaVersion: 6

env:
  browser: true

rules:
  max-len:
    - error
    - 100
    - 2
    - ignoreComments: true

  curly:
    - error
    - multi-or-nest
    - consistent

  brace-style:
    - error
    - stroustrup
    - allowSingleLine: true
